FROM python:3.11-slim

RUN apt-get update \
 && apt-get install -y \
      chromium \
      chromium-driver \
      curl \
      unzip \
      ca-certificates \
      wget \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY producer_scraper_1.py .

CMD ["sh", "-c", "sleep 100; while true; do python producer_scraper_1.py; sleep 35000; done"]
